package bridge

import (
	"bufio"
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// fixtureFiles are the golden JSONL corpora generated by
// testdata/gen-fixtures.mjs from the REAL `senpi --mode rpc` process. They are
// never hand-edited; regenerate with `node .../testdata/gen-fixtures.mjs`.
var fixtureFiles = []string{
	"response_get_state.jsonl",
	"response_get_commands.jsonl",
	"response_get_messages.jsonl",
	"response_error.jsonl",
	"events_prompt_turn.jsonl",
	"extension_error.jsonl",
	"demux_mixed.jsonl",
}

// readFixtureLines returns each JSONL record (without the trailing LF) from a
// golden file under testdata/.
func readFixtureLines(t *testing.T, name string) [][]byte {
	t.Helper()
	f, err := os.Open(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("open fixture %s: %v", name, err)
	}
	defer func() {
		if cerr := f.Close(); cerr != nil {
			t.Errorf("close fixture %s: %v", name, cerr)
		}
	}()

	var lines [][]byte
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1024*1024), 8*1024*1024)
	for sc.Scan() {
		line := sc.Bytes()
		if len(bytes.TrimSpace(line)) == 0 {
			continue
		}
		cp := make([]byte, len(line))
		copy(cp, line)
		lines = append(lines, cp)
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan fixture %s: %v", name, err)
	}
	if len(lines) == 0 {
		t.Fatalf("fixture %s had no records", name)
	}
	return lines
}

// TestDecodeEncodeRoundTripByteEqual asserts that every golden line decodes into
// a typed Message and re-encodes to BYTE-IDENTICAL JSON. This is the core codec
// fidelity gate: any dropped field, reordered key, or type coercion breaks it.
func TestDecodeEncodeRoundTripByteEqual(t *testing.T) {
	for _, name := range fixtureFiles {
		name := name
		t.Run(name, func(t *testing.T) {
			for i, line := range readFixtureLines(t, name) {
				msg, err := DecodeMessage(line)
				if err != nil {
					t.Fatalf("%s line %d: decode: %v\n  line: %s", name, i, err, line)
				}
				got, err := EncodeMessage(msg)
				if err != nil {
					t.Fatalf("%s line %d: encode: %v", name, i, err)
				}
				if !bytes.Equal(got, line) {
					t.Fatalf("%s line %d: round-trip not byte-equal\n  want: %s\n  got:  %s", name, i, line, got)
				}
			}
		})
	}
}

// TestJSONLCodecFramingRoundTrip asserts the JSONL framing layer (LF terminator,
// CR trimming, blank-line and malformed-line skipping) matches jsonl.ts.
func TestJSONLCodecFramingRoundTrip(t *testing.T) {
	lines := readFixtureLines(t, "events_prompt_turn.jsonl")

	// Serialize each record through the codec and reassemble the stream.
	var buf bytes.Buffer
	for _, line := range lines {
		msg, err := DecodeMessage(line)
		if err != nil {
			t.Fatalf("decode: %v", err)
		}
		framed, err := SerializeLine(msg)
		if err != nil {
			t.Fatalf("serialize: %v", err)
		}
		buf.Write(framed)
	}

	// A JSONL reader over the reassembled stream must yield the same records.
	r := NewLineReader(bytes.NewReader(buf.Bytes()))
	var got [][]byte
	for {
		rec, err := r.ReadLine()
		if err != nil {
			break
		}
		got = append(got, rec)
	}
	if len(got) != len(lines) {
		t.Fatalf("framing: read %d records, want %d", len(got), len(lines))
	}
}
