/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PtySession {
  constructor()
  write(data: string | Buffer | Uint8Array): NapiResult<undefined>
  resize(cols: number, rows: number): NapiResult<undefined>
  kill(signal?: string | undefined | null): NapiResult<undefined>
  waitExit(): NapiResult<Promise<unknown>>
  wait(): NapiResult<Promise<unknown>>
}
export type NativePtySession = PtySession

export declare function __senpiPtyV2026_7_5(): string

export interface NativePtyExit {
  exitCode?: number
  signal?: string
  cancelled: boolean
  timedOut: boolean
}

export interface NativePtySessionOptions {
  command: string
  args?: Array<string>
  cwd?: string
  env?: Record<string, string | undefined | null>
  cols: number
  rows: number
  timeoutMs?: number
}

export declare function startPtySession(options: NativePtySessionOptions, onData: (arg: Buffer) => void): NapiResult<PtySession>

export declare function version(): string
