export const BUILT_IN_PROVIDER_DISPLAY_NAMES: Record<string, string> = {
	"alibaba-coding-plan": "Alibaba Coding Plan",
	"amazon-bedrock": "Amazon Bedrock",
	"ant-ling": "Ant Ling",
	anthropic: "Anthropic",
	"azure-openai-responses": "Azure OpenAI Responses",
	cerebras: "Cerebras",
	"cloudflare-ai-gateway": "Cloudflare AI Gateway",
	"cloudflare-workers-ai": "Cloudflare Workers AI",
	cursor: "Cursor",
	deepinfra: "DeepInfra",
	deepseek: "DeepSeek",
	firepass: "Fire Pass",
	fireworks: "Fireworks",
	fugu: "Sakana Fugu",
	"gitlab-duo": "GitLab Duo",
	"glm-zcode": "GLM ZCode (Unofficial)",
	google: "Google Gemini",
	"google-antigravity": "Google Antigravity",
	"google-gemini-cli": "Google Gemini CLI (Cloud Code Assist)",
	"google-vertex": "Google Vertex AI",
	groq: "Groq",
	huggingface: "Hugging Face",
	kilo: "Kilo Gateway",
	"kimi-code": "Kimi Code",
	"kimi-coding": "Kimi For Coding",
	litellm: "LiteLLM",
	"lm-studio": "LM Studio",
	minimax: "MiniMax",
	"minimax-cn": "MiniMax (China)",
	"minimax-code": "MiniMax Coding Plan (International)",
	"minimax-code-cn": "MiniMax Coding Plan (China)",
	mistral: "Mistral",
	moonshot: "Moonshot (Kimi API)",
	moonshotai: "Moonshot AI",
	"moonshotai-cn": "Moonshot AI (China)",
	nanogpt: "NanoGPT",
	nvidia: "NVIDIA NIM",
	ollama: "Ollama",
	"ollama-cloud": "Ollama Cloud",
	openai: "OpenAI",
	"openai-codex-device": "OpenAI Codex (Device Code)",
	opencode: "OpenCode Zen",
	"opencode-go": "OpenCode Go",
	"opencode-zen": "OpenCode Zen",
	openrouter: "OpenRouter",
	perplexity: "Perplexity",
	qianfan: "Qianfan",
	"qwen-portal": "Qwen Portal",
	synthetic: "Synthetic",
	together: "Together AI",
	venice: "Venice",
	"vercel-ai-gateway": "Vercel AI Gateway",
	vllm: "vLLM",
	xai: "xAI",
	xiaomi: "Xiaomi MiMo",
	"xiaomi-token-plan-ams": "Xiaomi MiMo Token Plan (Amsterdam)",
	"xiaomi-token-plan-cn": "Xiaomi MiMo Token Plan (China)",
	"xiaomi-token-plan-sgp": "Xiaomi MiMo Token Plan (Singapore)",
	zai: "ZAI Coding Plan (Global)",
	"zai-coding-cn": "ZAI Coding Plan (China)",
	zenmux: "ZenMux",
};
