// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/alibaba-coding-plan.json" with { type: "json" };
import type { Model } from "../types.ts";

export const ALIBABA_CODING_PLAN_MODELS = values as {
	"qwen3.5-plus": Model<"openai-completions"> & {
		id: "qwen3.5-plus";
		provider: "alibaba-coding-plan";
	};
};
