// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cursor.json" with { type: "json" };
import type { Model } from "../types.ts";

export const CURSOR_MODELS = values as {
	"default": Model<"cursor-connect"> & {
		id: "default";
		provider: "cursor";
	};
};
