// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepinfra.json" with { type: "json" };
import type { Model } from "../types.ts";

export const DEEPINFRA_MODELS = values as {
	"deepseek-ai/DeepSeek-V3.2": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V3.2";
		provider: "deepinfra";
	};
};
