// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/fugu.json" with { type: "json" };
import type { Model } from "../types.ts";

export const FUGU_MODELS = values as {
	"fugu": Model<"openai-completions"> & {
		id: "fugu";
		provider: "fugu";
	};
};
