// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/gitlab-duo.json" with { type: "json" };
import type { Model } from "../types.ts";

export const GITLAB_DUO_MODELS = values as {
	"claude-sonnet-4-6": Model<"anthropic-messages"> & {
		id: "claude-sonnet-4-6";
		provider: "gitlab-duo";
	};
	"gpt-5.1-2025-11-13": Model<"openai-completions"> & {
		id: "gpt-5.1-2025-11-13";
		provider: "gitlab-duo";
	};
};
