// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const GITLAB_DUO_MODELS = {
	"claude-sonnet-4-6": {
		id: "claude-sonnet-4-6",
		name: "Claude Sonnet 4.6",
		api: "anthropic-messages",
		provider: "gitlab-duo",
		baseUrl: "https://cloud.gitlab.com/ai/v1/proxy/anthropic/",
		compat: {"forceAdaptiveThinking":true},
		reasoning: true,
		thinkingLevelMap: {"xhigh":"max","max":"max"},
		input: ["text", "image"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 64000,
	} satisfies Model<"anthropic-messages">,
	"gpt-5.1-2025-11-13": {
		id: "gpt-5.1-2025-11-13",
		name: "GPT-5.1",
		api: "openai-completions",
		provider: "gitlab-duo",
		baseUrl: "https://cloud.gitlab.com/ai/v1/proxy/openai/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 16384,
	} satisfies Model<"openai-completions">,
} as const;
