// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/google-antigravity.json" with { type: "json" };
import type { Model } from "../types.ts";

export const GOOGLE_ANTIGRAVITY_MODELS = values as {
	"claude-opus-4-5-thinking": Model<"google-gemini-cli"> & {
		id: "claude-opus-4-5-thinking";
		provider: "google-antigravity";
	};
	"claude-opus-4-6-thinking": Model<"google-gemini-cli"> & {
		id: "claude-opus-4-6-thinking";
		provider: "google-antigravity";
	};
	"claude-sonnet-4-5": Model<"google-gemini-cli"> & {
		id: "claude-sonnet-4-5";
		provider: "google-antigravity";
	};
	"claude-sonnet-4-5-thinking": Model<"google-gemini-cli"> & {
		id: "claude-sonnet-4-5-thinking";
		provider: "google-antigravity";
	};
	"claude-sonnet-4-6": Model<"google-gemini-cli"> & {
		id: "claude-sonnet-4-6";
		provider: "google-antigravity";
	};
	"claude-sonnet-4-6-thinking": Model<"google-gemini-cli"> & {
		id: "claude-sonnet-4-6-thinking";
		provider: "google-antigravity";
	};
	"gemini-2.5-flash": Model<"google-gemini-cli"> & {
		id: "gemini-2.5-flash";
		provider: "google-antigravity";
	};
	"gemini-2.5-flash-thinking": Model<"google-gemini-cli"> & {
		id: "gemini-2.5-flash-thinking";
		provider: "google-antigravity";
	};
	"gemini-2.5-pro": Model<"google-gemini-cli"> & {
		id: "gemini-2.5-pro";
		provider: "google-antigravity";
	};
	"gemini-3-flash": Model<"google-gemini-cli"> & {
		id: "gemini-3-flash";
		provider: "google-antigravity";
	};
	"gemini-3-pro-high": Model<"google-gemini-cli"> & {
		id: "gemini-3-pro-high";
		provider: "google-antigravity";
	};
	"gemini-3-pro-low": Model<"google-gemini-cli"> & {
		id: "gemini-3-pro-low";
		provider: "google-antigravity";
	};
	"gemini-3.1-pro-low": Model<"google-gemini-cli"> & {
		id: "gemini-3.1-pro-low";
		provider: "google-antigravity";
	};
	"gpt-oss-120b-medium": Model<"google-gemini-cli"> & {
		id: "gpt-oss-120b-medium";
		provider: "google-antigravity";
	};
};
