// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/google-gemini-cli.json" with { type: "json" };
import type { Model } from "../types.ts";

export const GOOGLE_GEMINI_CLI_MODELS = values as {
	"gemini-2.0-flash": Model<"google-gemini-cli"> & {
		id: "gemini-2.0-flash";
		provider: "google-gemini-cli";
	};
	"gemini-2.5-flash": Model<"google-gemini-cli"> & {
		id: "gemini-2.5-flash";
		provider: "google-gemini-cli";
	};
	"gemini-2.5-pro": Model<"google-gemini-cli"> & {
		id: "gemini-2.5-pro";
		provider: "google-gemini-cli";
	};
	"gemini-3-flash-preview": Model<"google-gemini-cli"> & {
		id: "gemini-3-flash-preview";
		provider: "google-gemini-cli";
	};
	"gemini-3-pro-preview": Model<"google-gemini-cli"> & {
		id: "gemini-3-pro-preview";
		provider: "google-gemini-cli";
	};
	"gemini-3.1-flash-lite-preview": Model<"google-gemini-cli"> & {
		id: "gemini-3.1-flash-lite-preview";
		provider: "google-gemini-cli";
	};
	"gemini-3.1-pro-preview": Model<"google-gemini-cli"> & {
		id: "gemini-3.1-pro-preview";
		provider: "google-gemini-cli";
	};
	"gemini-3.5-flash": Model<"google-gemini-cli"> & {
		id: "gemini-3.5-flash";
		provider: "google-gemini-cli";
	};
};
