// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const KILO_MODELS = {
	"anthropic/claude-sonnet-4.5": {
		id: "anthropic/claude-sonnet-4.5",
		name: "Claude Sonnet 4.5",
		api: "openai-completions",
		provider: "kilo",
		baseUrl: "https://api.kilo.ai/api/gateway",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 200000,
		maxTokens: 64000,
	} satisfies Model<"openai-completions">,
} as const;
