// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/kilo.json" with { type: "json" };
import type { Model } from "../types.ts";

export const KILO_MODELS = values as {
	"anthropic/claude-sonnet-4.5": Model<"openai-completions"> & {
		id: "anthropic/claude-sonnet-4.5";
		provider: "kilo";
	};
};
