// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/kimi-code.json" with { type: "json" };
import type { Model } from "../types.ts";

export const KIMI_CODE_MODELS = values as {
	"kimi-for-coding": Model<"openai-completions"> & {
		id: "kimi-for-coding";
		provider: "kimi-code";
	};
	"kimi-k2": Model<"openai-completions"> & {
		id: "kimi-k2";
		provider: "kimi-code";
	};
	"kimi-k2-turbo-preview": Model<"openai-completions"> & {
		id: "kimi-k2-turbo-preview";
		provider: "kimi-code";
	};
	"kimi-k2.5": Model<"openai-completions"> & {
		id: "kimi-k2.5";
		provider: "kimi-code";
	};
	"kimi-k2.7-code": Model<"openai-completions"> & {
		id: "kimi-k2.7-code";
		provider: "kimi-code";
	};
};
