// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/litellm.json" with { type: "json" };
import type { Model } from "../types.ts";

export const LITELLM_MODELS = values as {
	"claude-opus-4-6": Model<"openai-completions"> & {
		id: "claude-opus-4-6";
		provider: "litellm";
	};
};
