// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/lm-studio.json" with { type: "json" };
import type { Model } from "../types.ts";

export const LM_STUDIO_MODELS = values as {
	"llama-3-8b": Model<"openai-completions"> & {
		id: "llama-3-8b";
		provider: "lm-studio";
	};
};
