// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/minimax-code.json" with { type: "json" };
import type { Model } from "../types.ts";

export const MINIMAX_CODE_MODELS = values as {
	"MiniMax-M2.7": Model<"openai-completions"> & {
		id: "MiniMax-M2.7";
		provider: "minimax-code";
	};
	"MiniMax-M2.7-highspeed": Model<"openai-completions"> & {
		id: "MiniMax-M2.7-highspeed";
		provider: "minimax-code";
	};
	"MiniMax-M3": Model<"openai-completions"> & {
		id: "MiniMax-M3";
		provider: "minimax-code";
	};
};
