// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/moonshot.json" with { type: "json" };
import type { Model } from "../types.ts";

export const MOONSHOT_MODELS = values as {
	"kimi-k2-0711-preview": Model<"openai-completions"> & {
		id: "kimi-k2-0711-preview";
		provider: "moonshot";
	};
	"kimi-k2-0905-preview": Model<"openai-completions"> & {
		id: "kimi-k2-0905-preview";
		provider: "moonshot";
	};
	"kimi-k2-thinking": Model<"openai-completions"> & {
		id: "kimi-k2-thinking";
		provider: "moonshot";
	};
	"kimi-k2-thinking-turbo": Model<"openai-completions"> & {
		id: "kimi-k2-thinking-turbo";
		provider: "moonshot";
	};
	"kimi-k2-turbo-preview": Model<"openai-completions"> & {
		id: "kimi-k2-turbo-preview";
		provider: "moonshot";
	};
	"kimi-k2.5": Model<"openai-completions"> & {
		id: "kimi-k2.5";
		provider: "moonshot";
	};
	"kimi-k2.6": Model<"openai-completions"> & {
		id: "kimi-k2.6";
		provider: "moonshot";
	};
	"kimi-k2.7-code": Model<"openai-completions"> & {
		id: "kimi-k2.7-code";
		provider: "moonshot";
	};
	"kimi-k2.7-code-highspeed": Model<"openai-completions"> & {
		id: "kimi-k2.7-code-highspeed";
		provider: "moonshot";
	};
	"kimi-k3": Model<"openai-completions"> & {
		id: "kimi-k3";
		provider: "moonshot";
	};
};
