// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/nanogpt.json" with { type: "json" };
import type { Model } from "../types.ts";

export const NANOGPT_MODELS = values as {
	"openai/gpt-5.4": Model<"openai-completions"> & {
		id: "openai/gpt-5.4";
		provider: "nanogpt";
	};
};
