// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/opencode-zen.json" with { type: "json" };
import type { Model } from "../types.ts";

export const OPENCODE_ZEN_MODELS = values as {
	"big-pickle": Model<"openai-completions"> & {
		id: "big-pickle";
		provider: "opencode-zen";
	};
	"claude-fable-5": Model<"anthropic-messages"> & {
		id: "claude-fable-5";
		provider: "opencode-zen";
	};
	"claude-haiku-4-5": Model<"anthropic-messages"> & {
		id: "claude-haiku-4-5";
		provider: "opencode-zen";
	};
	"claude-opus-4-1": Model<"anthropic-messages"> & {
		id: "claude-opus-4-1";
		provider: "opencode-zen";
	};
	"claude-opus-4-5": Model<"anthropic-messages"> & {
		id: "claude-opus-4-5";
		provider: "opencode-zen";
	};
	"claude-opus-4-6": Model<"anthropic-messages"> & {
		id: "claude-opus-4-6";
		provider: "opencode-zen";
	};
	"claude-opus-4-7": Model<"anthropic-messages"> & {
		id: "claude-opus-4-7";
		provider: "opencode-zen";
	};
	"claude-opus-4-8": Model<"anthropic-messages"> & {
		id: "claude-opus-4-8";
		provider: "opencode-zen";
	};
	"claude-sonnet-4": Model<"anthropic-messages"> & {
		id: "claude-sonnet-4";
		provider: "opencode-zen";
	};
	"claude-sonnet-4-5": Model<"anthropic-messages"> & {
		id: "claude-sonnet-4-5";
		provider: "opencode-zen";
	};
	"claude-sonnet-4-6": Model<"anthropic-messages"> & {
		id: "claude-sonnet-4-6";
		provider: "opencode-zen";
	};
	"claude-sonnet-5": Model<"anthropic-messages"> & {
		id: "claude-sonnet-5";
		provider: "opencode-zen";
	};
	"deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-v4-flash";
		provider: "opencode-zen";
	};
	"deepseek-v4-flash-free": Model<"openai-completions"> & {
		id: "deepseek-v4-flash-free";
		provider: "opencode-zen";
	};
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "opencode-zen";
	};
	"gemini-3-flash": Model<"google-generative-ai"> & {
		id: "gemini-3-flash";
		provider: "opencode-zen";
	};
	"gemini-3.1-pro": Model<"google-generative-ai"> & {
		id: "gemini-3.1-pro";
		provider: "opencode-zen";
	};
	"gemini-3.5-flash": Model<"google-generative-ai"> & {
		id: "gemini-3.5-flash";
		provider: "opencode-zen";
	};
	"glm-5": Model<"openai-completions"> & {
		id: "glm-5";
		provider: "opencode-zen";
	};
	"glm-5.1": Model<"openai-completions"> & {
		id: "glm-5.1";
		provider: "opencode-zen";
	};
	"glm-5.2": Model<"openai-completions"> & {
		id: "glm-5.2";
		provider: "opencode-zen";
	};
	"gpt-5": Model<"openai-responses"> & {
		id: "gpt-5";
		provider: "opencode-zen";
	};
	"gpt-5-codex": Model<"openai-responses"> & {
		id: "gpt-5-codex";
		provider: "opencode-zen";
	};
	"gpt-5-nano": Model<"openai-responses"> & {
		id: "gpt-5-nano";
		provider: "opencode-zen";
	};
	"gpt-5.1": Model<"openai-responses"> & {
		id: "gpt-5.1";
		provider: "opencode-zen";
	};
	"gpt-5.1-codex": Model<"openai-responses"> & {
		id: "gpt-5.1-codex";
		provider: "opencode-zen";
	};
	"gpt-5.1-codex-max": Model<"openai-responses"> & {
		id: "gpt-5.1-codex-max";
		provider: "opencode-zen";
	};
	"gpt-5.1-codex-mini": Model<"openai-responses"> & {
		id: "gpt-5.1-codex-mini";
		provider: "opencode-zen";
	};
	"gpt-5.2": Model<"openai-responses"> & {
		id: "gpt-5.2";
		provider: "opencode-zen";
	};
	"gpt-5.2-codex": Model<"openai-responses"> & {
		id: "gpt-5.2-codex";
		provider: "opencode-zen";
	};
	"gpt-5.3-codex": Model<"openai-responses"> & {
		id: "gpt-5.3-codex";
		provider: "opencode-zen";
	};
	"gpt-5.4": Model<"openai-responses"> & {
		id: "gpt-5.4";
		provider: "opencode-zen";
	};
	"gpt-5.4-mini": Model<"openai-responses"> & {
		id: "gpt-5.4-mini";
		provider: "opencode-zen";
	};
	"gpt-5.4-nano": Model<"openai-responses"> & {
		id: "gpt-5.4-nano";
		provider: "opencode-zen";
	};
	"gpt-5.4-pro": Model<"openai-responses"> & {
		id: "gpt-5.4-pro";
		provider: "opencode-zen";
	};
	"gpt-5.5": Model<"openai-responses"> & {
		id: "gpt-5.5";
		provider: "opencode-zen";
	};
	"gpt-5.5-pro": Model<"openai-responses"> & {
		id: "gpt-5.5-pro";
		provider: "opencode-zen";
	};
	"gpt-5.6-luna": Model<"openai-responses"> & {
		id: "gpt-5.6-luna";
		provider: "opencode-zen";
	};
	"gpt-5.6-sol": Model<"openai-responses"> & {
		id: "gpt-5.6-sol";
		provider: "opencode-zen";
	};
	"gpt-5.6-terra": Model<"openai-responses"> & {
		id: "gpt-5.6-terra";
		provider: "opencode-zen";
	};
	"grok-4.5": Model<"openai-completions"> & {
		id: "grok-4.5";
		provider: "opencode-zen";
	};
	"grok-build-0.1": Model<"openai-completions"> & {
		id: "grok-build-0.1";
		provider: "opencode-zen";
	};
	"hy3-free": Model<"openai-completions"> & {
		id: "hy3-free";
		provider: "opencode-zen";
	};
	"kimi-k2.5": Model<"openai-completions"> & {
		id: "kimi-k2.5";
		provider: "opencode-zen";
	};
	"kimi-k2.6": Model<"openai-completions"> & {
		id: "kimi-k2.6";
		provider: "opencode-zen";
	};
	"kimi-k2.7-code": Model<"openai-completions"> & {
		id: "kimi-k2.7-code";
		provider: "opencode-zen";
	};
	"mimo-v2.5-free": Model<"openai-completions"> & {
		id: "mimo-v2.5-free";
		provider: "opencode-zen";
	};
	"minimax-m2.5": Model<"openai-completions"> & {
		id: "minimax-m2.5";
		provider: "opencode-zen";
	};
	"minimax-m2.7": Model<"openai-completions"> & {
		id: "minimax-m2.7";
		provider: "opencode-zen";
	};
	"minimax-m3": Model<"openai-completions"> & {
		id: "minimax-m3";
		provider: "opencode-zen";
	};
	"nemotron-3-ultra-free": Model<"openai-completions"> & {
		id: "nemotron-3-ultra-free";
		provider: "opencode-zen";
	};
	"north-mini-code-free": Model<"openai-completions"> & {
		id: "north-mini-code-free";
		provider: "opencode-zen";
	};
	"qwen3.5-plus": Model<"anthropic-messages"> & {
		id: "qwen3.5-plus";
		provider: "opencode-zen";
	};
	"qwen3.6-plus": Model<"anthropic-messages"> & {
		id: "qwen3.6-plus";
		provider: "opencode-zen";
	};
};
