// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const PERPLEXITY_MODELS = {
	"sonar-pro": {
		id: "sonar-pro",
		name: "Sonar Pro",
		api: "openai-completions",
		provider: "perplexity",
		baseUrl: "https://api.perplexity.ai",
		reasoning: false,
		input: ["text"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 200000,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
} as const;
