// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/perplexity.json" with { type: "json" };
import type { Model } from "../types.ts";

export const PERPLEXITY_MODELS = values as {
	"sonar-pro": Model<"openai-completions"> & {
		id: "sonar-pro";
		provider: "perplexity";
	};
};
