// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qianfan.json" with { type: "json" };
import type { Model } from "../types.ts";

export const QIANFAN_MODELS = values as {
	"deepseek-v3.2": Model<"openai-completions"> & {
		id: "deepseek-v3.2";
		provider: "qianfan";
	};
};
