// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen-portal.json" with { type: "json" };
import type { Model } from "../types.ts";

export const QWEN_PORTAL_MODELS = values as {
	"coder-model": Model<"openai-completions"> & {
		id: "coder-model";
		provider: "qwen-portal";
	};
};
