// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/synthetic.json" with { type: "json" };
import type { Model } from "../types.ts";

export const SYNTHETIC_MODELS = values as {
	"hf:moonshotai/Kimi-K2.5": Model<"openai-completions"> & {
		id: "hf:moonshotai/Kimi-K2.5";
		provider: "synthetic";
	};
};
