// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/venice.json" with { type: "json" };
import type { Model } from "../types.ts";

export const VENICE_MODELS = values as {
	"llama-3.3-70b": Model<"openai-completions"> & {
		id: "llama-3.3-70b";
		provider: "venice";
	};
};
