// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/vllm.json" with { type: "json" };
import type { Model } from "../types.ts";

export const VLLM_MODELS = values as {
	"gpt-oss-20b": Model<"openai-completions"> & {
		id: "gpt-oss-20b";
		provider: "vllm";
	};
};
