// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zenmux.json" with { type: "json" };
import type { Model } from "../types.ts";

export const ZENMUX_MODELS = values as {
	"anthropic/claude-opus-4.6": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-4.6";
		provider: "zenmux";
	};
};
